<?php
/**
 * FAXDeliveryReceiptRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FAXDeliveryReceiptRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FAXDeliveryReceiptRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for faxDeliveryReceiptAutomationDelete
     *
     * Delete fax delivery receipt automation.
     *
     */
    public function testFaxDeliveryReceiptAutomationDelete()
    {
    }

    /**
     * Test case for faxDeliveryReceiptAutomationGet
     *
     * Get specific fax delivery receipt automation.
     *
     */
    public function testFaxDeliveryReceiptAutomationGet()
    {
    }

    /**
     * Test case for faxDeliveryReceiptAutomationPost
     *
     * Create fax delivery receipt automations.
     *
     */
    public function testFaxDeliveryReceiptAutomationPost()
    {
    }

    /**
     * Test case for faxDeliveryReceiptAutomationPut
     *
     * Update fax delivery receipt automation.
     *
     */
    public function testFaxDeliveryReceiptAutomationPut()
    {
    }

    /**
     * Test case for faxDeliveryReceiptAutomationsGet
     *
     * Get all fax delivery receipt automations.
     *
     */
    public function testFaxDeliveryReceiptAutomationsGet()
    {
    }
}
