<?php
/**
 * SMSDeliveryReceiptRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SMSDeliveryReceiptRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SMSDeliveryReceiptRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for smsDeliveryReceiptAutomationDelete
     *
     * Delete sms delivery receipt automation.
     *
     */
    public function testSmsDeliveryReceiptAutomationDelete()
    {
    }

    /**
     * Test case for smsDeliveryReceiptAutomationGet
     *
     * Get specific sms delivery receipt automation.
     *
     */
    public function testSmsDeliveryReceiptAutomationGet()
    {
    }

    /**
     * Test case for smsDeliveryReceiptAutomationPost
     *
     * Create sms delivery receipt automations.
     *
     */
    public function testSmsDeliveryReceiptAutomationPost()
    {
    }

    /**
     * Test case for smsDeliveryReceiptAutomationPut
     *
     * Update sms delivery receipt automation.
     *
     */
    public function testSmsDeliveryReceiptAutomationPut()
    {
    }

    /**
     * Test case for smsDeliveryReceiptAutomationsGet
     *
     * Get all sms delivery receipt automations.
     *
     */
    public function testSmsDeliveryReceiptAutomationsGet()
    {
    }
}
