<?php
/**
 * VoiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend.Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend.Client;

use \ClickSend.Client\Configuration;
use \ClickSend.Client\ApiException;
use \ClickSend.Client\ObjectSerializer;

/**
 * VoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend.Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VoiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for voiceCancelAllPut
     *
     * Update all voice messages as cancelled.
     *
     */
    public function testVoiceCancelAllPut()
    {
    }

    /**
     * Test case for voiceCancelByMessageIdPut
     *
     * Update voice message status as cancelled.
     *
     */
    public function testVoiceCancelByMessageIdPut()
    {
    }

    /**
     * Test case for voiceHistoryExportGet
     *
     * Export voice history.
     *
     */
    public function testVoiceHistoryExportGet()
    {
    }

    /**
     * Test case for voiceHistoryGet
     *
     * Get all voice history.
     *
     */
    public function testVoiceHistoryGet()
    {
    }

    /**
     * Test case for voiceLangGet
     *
     * Get all voice languages.
     *
     */
    public function testVoiceLangGet()
    {
    }

    /**
     * Test case for voicePricePost
     *
     * Calculate voice price.
     *
     */
    public function testVoicePricePost()
    {
    }

    /**
     * Test case for voiceReceiptsGet
     *
     * Get all voice receipts.
     *
     */
    public function testVoiceReceiptsGet()
    {
    }

    /**
     * Test case for voiceSendPost
     *
     * Send voice message(s).
     *
     */
    public function testVoiceSendPost()
    {
    }
}
