<?php
/**
 * InboundSMSRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * ClickSend Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClickSend;

/**
 * InboundSMSRuleTest Class Doc Comment
 *
 * @category    Class
 * @description Model for Inbound SMS Rules
 * @package     ClickSend
 * @author      ClickSend Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InboundSMSRuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InboundSMSRule"
     */
    public function testInboundSMSRule()
    {
    }

    /**
     * Test attribute "dedicated_number"
     */
    public function testPropertyDedicatedNumber()
    {
    }

    /**
     * Test attribute "rule_name"
     */
    public function testPropertyRuleName()
    {
    }

    /**
     * Test attribute "message_search_type"
     */
    public function testPropertyMessageSearchType()
    {
    }

    /**
     * Test attribute "message_search_term"
     */
    public function testPropertyMessageSearchTerm()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "action_address"
     */
    public function testPropertyActionAddress()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }
}
