<?php
/**
 * PostRecipientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClickSend;

/**
 * PostRecipientTest Class Doc Comment
 *
 * @category    Class
 * @description PostRecipient model
 * @package     ClickSend
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostRecipientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostRecipient"
     */
    public function testPostRecipient()
    {
    }

    /**
     * Test attribute "address_name"
     */
    public function testPropertyAddressName()
    {
    }

    /**
     * Test attribute "address_line_1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "address_line_2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "address_city"
     */
    public function testPropertyAddressCity()
    {
    }

    /**
     * Test attribute "address_state"
     */
    public function testPropertyAddressState()
    {
    }

    /**
     * Test attribute "address_postal_code"
     */
    public function testPropertyAddressPostalCode()
    {
    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {
    }

    /**
     * Test attribute "return_address_id"
     */
    public function testPropertyReturnAddressId()
    {
    }

    /**
     * Test attribute "schedule"
     */
    public function testPropertySchedule()
    {
    }
}
