<?php
/*
 * ClickSendV3APILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */

namespace ClickSendV3APILib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://rest.clicksend.com/v3/';

    //your username
    //TODO: Replace the $username with an appropriate value
    public static $username = 'TODO: Replace';

    //your api key
    //TODO: Replace the $key with an appropriate value
    public static $key = 'TODO: Replace';

}
