<?php
/**
 * InboundFAXRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * ClickSend Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend;

use \ClickSend\Configuration;
use \ClickSend\ApiException;
use \ClickSend\ObjectSerializer;

/**
 * InboundFAXRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundFAXRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for faxInboundAutomationDelete
     *
     * Delete inbound fax automation.
     *
     */
    public function testFaxInboundAutomationDelete()
    {
    }

    /**
     * Test case for faxInboundAutomationGet
     *
     * Get specific inbound fax automation.
     *
     */
    public function testFaxInboundAutomationGet()
    {
    }

    /**
     * Test case for faxInboundAutomationPost
     *
     * Create new inbound fax automation.
     *
     */
    public function testFaxInboundAutomationPost()
    {
    }

    /**
     * Test case for faxInboundAutomationPut
     *
     * Update inbound fax automation.
     *
     */
    public function testFaxInboundAutomationPut()
    {
    }

    /**
     * Test case for faxInboundAutomationsGet
     *
     * Get all inbound fax automations.
     *
     */
    public function testFaxInboundAutomationsGet()
    {
    }
}
