<?php
/**
 * MmsCampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * ClickSend Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend;

use \ClickSend\Configuration;
use \ClickSend\ApiException;
use \ClickSend\ObjectSerializer;

/**
 * MmsCampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MmsCampaignApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for mmsCampaignByMmsCampaignIdGet
     *
     * Get specific mms campaign.
     *
     */
    public function testMmsCampaignByMmsCampaignIdGet()
    {
    }

    /**
     * Test case for mmsCampaignsByMmsCampaignIdPut
     *
     * Update mms campaign.
     *
     */
    public function testMmsCampaignsByMmsCampaignIdPut()
    {
    }

    /**
     * Test case for mmsCampaignsCancelByMmsCampaignIdPut
     *
     * Cancel mms campaign.
     *
     */
    public function testMmsCampaignsCancelByMmsCampaignIdPut()
    {
    }

    /**
     * Test case for mmsCampaignsGet
     *
     * Get list of mms campaigns.
     *
     */
    public function testMmsCampaignsGet()
    {
    }

    /**
     * Test case for mmsCampaignsPricePost
     *
     * Calculate price for mms campaign.
     *
     */
    public function testMmsCampaignsPricePost()
    {
    }

    /**
     * Test case for mmsCampaignsSendPost
     *
     * Create mms campaign.
     *
     */
    public function testMmsCampaignsSendPost()
    {
    }
}
