<?php
/**
 * VoiceDeliveryReceiptRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ClickSend v3 REST API
 *
 * This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * ClickSend Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ClickSend;

use \ClickSend\Configuration;
use \ClickSend\ApiException;
use \ClickSend\ObjectSerializer;

/**
 * VoiceDeliveryReceiptRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClickSend
 * @author   ClickSend Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VoiceDeliveryReceiptRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for voiceDeliveryReceiptAutomationDelete
     *
     * Delete voice delivery receipt automation.
     *
     */
    public function testVoiceDeliveryReceiptAutomationDelete()
    {
    }

    /**
     * Test case for voiceDeliveryReceiptAutomationGet
     *
     * Get specific voice delivery receipt automation.
     *
     */
    public function testVoiceDeliveryReceiptAutomationGet()
    {
    }

    /**
     * Test case for voiceDeliveryReceiptAutomationPost
     *
     * Create voice delivery receipt automations.
     *
     */
    public function testVoiceDeliveryReceiptAutomationPost()
    {
    }

    /**
     * Test case for voiceDeliveryReceiptAutomationPut
     *
     * Update voice delivery receipt automation.
     *
     */
    public function testVoiceDeliveryReceiptAutomationPut()
    {
    }

    /**
     * Test case for voiceDeliveryReceiptAutomationsGet
     *
     * Get all voice delivery receipt automations.
     *
     */
    public function testVoiceDeliveryReceiptAutomationsGet()
    {
    }
}
